[context.production.environment] 
  CI="false"
  REACT_APP_TOKEN_SALE_PAGE="https://sale.supremacy.game"
  REACT_APP_SUPREMACY_PAGE="https://supremacy.game/"
  REACT_APP_GAME_SERVER_HOSTNAME = "api.supremacy.game"
  REACT_APP_PASSPORT_WEB = "https://passport.xsyn.io/"
  REACT_APP_PASSPORT_SERVER_HOST = "api.xsyn.io"
  REACT_APP_STREAM_SITE = "https://video.ninja-cdn.com:5443/WebRTCAppEE/play.html?name=R3dvaIhZOxRr1645381571194"
  REACT_APP_STREAM_SITE_OFFICE = "https://watch-local-am.supremacy.game:5443/WebRTCAppEE/play.html?name=524280586954581049507513"
  REACT_APP_SENTRY_DSN_FRONTEND = "https://326f24205fe94d2093775e0228384359@o370480.ingest.sentry.io/6194703"
  REACT_APP_SENTRY_ENVIRONMENT = "production"
  REACT_APP_SENTRY_SAMPLERATE = "1"
  REACT_APP_SERVER_HOST_IMAGES = "https://api.xsyn.io"
  REACT_APP_MAINTENANCE_PAGE = "true"
[context.staging.environment]
  CI="false"
  REACT_APP_TOKEN_SALE_PAGE="https://sale.supremacy.game"
  REACT_APP_SUPREMACY_PAGE="https://supremacy.game/"
  REACT_APP_GAME_SERVER_HOSTNAME = "staging-api.supremacy.game"
  REACT_APP_PASSPORT_WEB = "https://staging--staging-passport.netlify.app/"
  REACT_APP_PASSPORT_SERVER_HOST = "staging-passport.xsyn.io"
  REACT_APP_STREAM_SITE = "https://video.ninja-cdn.com:5443/WebRTCAppEE/play.html?name=R3dvaIhZOxRr1645381571194"
  REACT_APP_STREAM_SITE_OFFICE = "https://watch-local-am.supremacy.game:5443/WebRTCAppEE/play.html?name=524280586954581049507513"
  REACT_APP_SENTRY_DSN_FRONTEND = "https://326f24205fe94d2093775e0228384359@o370480.ingest.sentry.io/6194703"
  REACT_APP_SENTRY_ENVIRONMENT = "staging"
  REACT_APP_SENTRY_SAMPLERATE = "1"
  REACT_APP_SERVER_HOST_IMAGES = "https://staging-passport.xsyn.io"
  REACT_APP_MAINTENANCE_PAGE = "false"
