[context.production.environment] 
  CI="false"
  REACT_APP_TOKEN_SALE_PAGE="https://passport.xsyn.io/external/buy"
  REACT_APP_SUPREMACY_PAGE="https://supremacy.game/"
  REACT_APP_GAME_SERVER_HOSTNAME="api.supremacy.game"
  REACT_APP_PASSPORT_WEB="https://passport.xsyn.io/"
  REACT_APP_PASSPORT_SERVER_HOST="api.passport.supremacy.game"
  REACT_APP_STREAM_SITE="https://video.ninja-cdn.com:5443/WebRTCAppEE/play.html?name=R3dvaIhZOxRr1645381571194"
  REACT_APP_STREAM_SITE_OFFICE="https://watch-local-am.supremacy.game:5443/WebRTCAppEE/play.html?name=524280586954581049507513"
  REACT_APP_SENTRY_DSN_FRONTEND="https://326f24205fe94d2093775e0228384359@o370480.ingest.sentry.io/6194703"
  REACT_APP_SENTRY_ENVIRONMENT="production"
  REACT_APP_SENTRY_SAMPLERATE="1"
  REACT_APP_SERVER_HOST_IMAGES="https://api.xsyn.io"
  REACT_APP_MAINTENANCE_PAGE="false"
  REACT_APP_PRISMIC_ACCESS_TOKEN="MC5ZaEMyMFJFQUFDSUFXZUhm.77-977-977-9FUdeBxkUThw_b17vv70A77-9Se-_ve-_ve-_vSDvv73vv73vv71dTzwqXnZu"
  REACT_APP_TELEGRAM_BOT_URL="https://t.me/SupremacyNotificationsBot"
  REACT_APP_ENVIRONMENT="production"
  REACT_APP_CAPTCHA_SITE_KEY="dc2798ab-c560-4cfd-b78b-3c5901e1a535"
  REACT_APP_STRIPE_PUBLISHABLE_KEY="pk_live_51K4KcfCHhHY2zbVVUOyt8fEnXQcbpeNSvjzoIHc9h2WlZNfWmzCLljOhJB9Le78iS2aLRfoNSuKouF8mPpwSyw3b00rrcCH6SJ"
[context.staging.environment]
  CI="false"
  REACT_APP_TOKEN_SALE_PAGE="https://passport.xsyn.io/external/buy"
  REACT_APP_SUPREMACY_PAGE="https://supremacy.game/"
  REACT_APP_GAME_SERVER_HOSTNAME="api.supremacygame.dev"
  REACT_APP_PASSPORT_WEB="https://staging.xsyn.dev/"
  REACT_APP_PASSPORT_SERVER_HOST="passport.supremacygame.dev"
  REACT_APP_STREAM_SITE="https://video.ninja-cdn.com:5443/WebRTCAppEE/play.html?name=R3dvaIhZOxRr1645381571194"
  REACT_APP_STREAM_SITE_OFFICE="https://watch-local-am.supremacy.game:5443/WebRTCAppEE/play.html?name=524280586954581049507513"
  REACT_APP_SENTRY_DSN_FRONTEND="https://326f24205fe94d2093775e0228384359@o370480.ingest.sentry.io/6194703"
  REACT_APP_SENTRY_ENVIRONMENT="staging"
  REACT_APP_SENTRY_SAMPLERATE="1"
  REACT_APP_SERVER_HOST_IMAGES="https://passport.supremacygame.dev"
  REACT_APP_MAINTENANCE_PAGE="false"
  REACT_APP_PRISMIC_ACCESS_TOKEN="MC5ZaEMyMFJFQUFDSUFXZUhm.77-977-977-9FUdeBxkUThw_b17vv70A77-9Se-_ve-_ve-_vSDvv73vv73vv71dTzwqXnZu"
  REACT_APP_TELEGRAM_BOT_URL= "https://t.me/SupremacyNotifyBot"
  REACT_APP_ENVIRONMENT="staging"
  REACT_APP_CAPTCHA_SITE_KEY="76234527-a022-4392-a254-9f9328dd63bf"
  REACT_APP_STRIPE_PUBLISHABLE_KEY="pk_test_51K4KcfCHhHY2zbVVAun2XBRv1X54CmeCm6dXlQlc42yhvwG4hHRCtafU0gFI53i2mfPVZYQPeUd1xdfyT8mD6XBF004SqFkRhL"