# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reviewdog

on:
  pull_request:
    branches: [ develop, staging, main ]
    
env:
  NINJA_NPM_TOKEN: ${{ secrets.NINJA_NPM_TOKEN }}
  FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-pr-review # Change reporter.
          level: info
          eslint_flags: 'src/'
      - name: Run Prettier
        run: npm run format-check