name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"
      - "!*-rc*"

permissions:
  contents: write

env:
  NINJA_NPM_TOKEN: ${{ secrets.NINJA_NPM_TOKEN }}
  REACT_APP_GAME_SERVER_HOST: api.supremacy.game
  REACT_APP_PASSPORT_WEB: https://passport.xsyn.io
  REACT_APP_PASSPORT_SERVER_HOST: passport.xsyn.io
  REACT_APP_STREAM_SITE: https://watch-syd02.supremacy.game/WebRTCAppEE/play.html?name=886200805704583109786601
  REACT_APP_STREAM_SITE_OFFICE: https://watch-local-am.supremacy.game:5443/WebRTCAppEE/play.html?name=524280586954581049507513

  REACT_APP_SENTRY_DSN_FRONTEND: https://326f24205fe94d2093775e0228384359@o370480.ingest.sentry.io/6194703
  REACT_APP_SENTRY_ENVIRONMENT: production
  REACT_APP_SENTRY_SAMPLERATE: 1

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      
      # cache npm dependencies
      # https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
      - name: Cache npm
        if: ${{ !env.ACT }} # if running in local test environment
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('./package-lock.json') }}

      - name: Install npm packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Collect meta data
        run: |
          echo "GITVERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "REACT_APP_SENTRY_CURRENT_RELEASE_NAME=supremacy-supremacy_stream_site@$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build web
        run: CI=false BUILD_PATH='deploy/web' npm run build
      
      - name: Add other files
        run: |  
          cp -r ./config ./deploy/.

      - name: Tar Gzip
        run: |
          mv deploy supremacy-stream-site_${{env.GITVERSION}}
          tar czf supremacy-stream-site_${{env.GITVERSION}}.tar.gz supremacy-stream-site_${{env.GITVERSION}}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: streamsite_${{env.GITVERSION}}.tar.gz
          generate_release_notes: true
